
abi=[{"constant": True, "inputs": [], "name": "name",
                                                    "outputs": [{"name": "", "type": "string", "value": "TNC1"}],
                                                    "payable": False, "stateMutability": "view", "type": "function"},
                                                   {"constant": False,
                                                    "inputs": [{"name": "_spender", "type": "address"},
                                                               {"name": "_value", "type": "uint256"}],
                                                    "name": "approve", "outputs": [{"name": "success", "type": "bool"}],
                                                    "payable": False, "stateMutability": "nonpayable",
                                                    "type": "function"},
                                                   {"constant": True, "inputs": [], "name": "totalSupply",
                                                    "outputs": [{"name": "", "type": "uint256", "value": "1e+36"}],
                                                    "payable": False, "stateMutability": "view", "type": "function"},
                                                   {"constant": False, "inputs": [{"name": "_from", "type": "address"},
                                                                                  {"name": "_to", "type": "address"},
                                                                                  {"name": "_value",
                                                                                   "type": "uint256"}],
                                                    "name": "transferFrom",
                                                    "outputs": [{"name": "success", "type": "bool"}], "payable": False,
                                                    "stateMutability": "nonpayable", "type": "function"},
                                                   {"constant": True, "inputs": [], "name": "decimals",
                                                    "outputs": [{"name": "", "type": "uint8", "value": "18"}],
                                                    "payable": False, "stateMutability": "view", "type": "function"},
                                                   {"constant": False,
                                                    "inputs": [{"name": "_value", "type": "uint256"}], "name": "burn",
                                                    "outputs": [{"name": "success", "type": "bool"}], "payable": False,
                                                    "stateMutability": "nonpayable", "type": "function"},
                                                   {"constant": True, "inputs": [{"name": "", "type": "address"}],
                                                    "name": "balanceOf",
                                                    "outputs": [{"name": "", "type": "uint256", "value": "0"}],
                                                    "payable": False, "stateMutability": "view", "type": "function"},
                                                   {"constant": False, "inputs": [{"name": "_from", "type": "address"},
                                                                                  {"name": "_value",
                                                                                   "type": "uint256"}],
                                                    "name": "burnFrom",
                                                    "outputs": [{"name": "success", "type": "bool"}], "payable": False,
                                                    "stateMutability": "nonpayable", "type": "function"},
                                                   {"constant": True, "inputs": [], "name": "symbol",
                                                    "outputs": [{"name": "", "type": "string", "value": "TNC1"}],
                                                    "payable": False, "stateMutability": "view", "type": "function"},
                                                   {"constant": False, "inputs": [{"name": "_to", "type": "address"},
                                                                                  {"name": "_value",
                                                                                   "type": "uint256"}],
                                                    "name": "transfer", "outputs": [], "payable": False,
                                                    "stateMutability": "nonpayable", "type": "function"},
                                                   {"constant": False,
                                                    "inputs": [{"name": "_spender", "type": "address"},
                                                               {"name": "_value", "type": "uint256"},
                                                               {"name": "_extraData", "type": "bytes"}],
                                                    "name": "approveAndCall",
                                                    "outputs": [{"name": "success", "type": "bool"}], "payable": False,
                                                    "stateMutability": "nonpayable", "type": "function"},
                                                   {"constant": True, "inputs": [{"name": "", "type": "address"},
                                                                                 {"name": "", "type": "address"}],
                                                    "name": "allowance",
                                                    "outputs": [{"name": "", "type": "uint256", "value": "0"}],
                                                    "payable": False, "stateMutability": "view", "type": "function"}, {
                                                       "inputs": [
                                                           {"name": "initialSupply", "type": "uint256", "index": 0,
                                                            "typeShort": "uint", "bits": "256",
                                                            "displayName": "initial Supply",
                                                            "template": "elements_input_uint",
                                                            "value": "1000000000000000000"},
                                                           {"name": "tokenName", "type": "string", "index": 1,
                                                            "typeShort": "string", "bits": "",
                                                            "displayName": "token Name",
                                                            "template": "elements_input_string", "value": "TNC1"},
                                                           {"name": "tokenSymbol", "type": "string", "index": 2,
                                                            "typeShort": "string", "bits": "",
                                                            "displayName": "token Symbol",
                                                            "template": "elements_input_string", "value": "TNC1"}],
                                                       "payable": False, "stateMutability": "nonpayable",
                                                       "type": "constructor"}, {"anonymous": False, "inputs": [
                                                      {"indexed": True, "name": "from", "type": "address"},
                                                      {"indexed": True, "name": "to", "type": "address"},
                                                      {"indexed": False, "name": "value", "type": "uint256"}],
                                                                                "name": "Transfer", "type": "event"},
                                                   {"anonymous": False,
                                                    "inputs": [{"indexed": False, "name": "value", "type": "uint256"}],
                                                    "name": "Logger", "type": "event"}, {"anonymous": False, "inputs": [
                                                      {"indexed": True, "name": "from", "type": "address"},
                                                      {"indexed": False, "name": "value", "type": "uint256"}],
                                                                                         "name": "Burn",
                                                                                         "type": "event"}]


SmartContract={
    "ERC20TNC":("0x8AB0FC62b95AA25EE0FBd80eDc1252DDa670Aa6C",abi)
}

ABI_MAPPING={
    "0x8AB0FC62b95AA25EE0FBd80eDc1252DDa670Aa6C":abi
}